### ISSUE TITLE
After update doesn't show up

### ISSUE THREAD

**Issue by 123top** [revilheart/rhSGST#1]
After the update to 4.0 it shows nothing on [steamgifts](https://www.steamgifts.com/). It is like I have no script installed. I use it on Google Chrome with Tampermonkey.

**Comment by revilheart** [comment]
Any errors in the console?

**Comment by Matth46** [comment]
ERROR: Execution of script 'rhSGST' failed! Cannot read property 'FE' of undefined

**Comment by revilheart** [comment]
Should be fixed in v4.0.2.

**Comment by 123top** [comment]
fixed 

thx for fast response :)
