### ISSUE TITLE
[Request] Either/Or....Disable Option..?

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#10]
Any chance i can either get a disablement of the anti-fading solution you did for avatar popout, or a disablement for avatar popout on the GA pages where it needed that anti-fading solution.  (second one may still require the first, i'm not sure / whatever is easier)

basically i don't like the hovering of it causing it to unfade making me think i haven't joined it, but wish to keep avatar popout for discussions where there is no joined GAs to cause that fade issue.  i know i'm a pain in the ass, but whichever is easier for you if that helps. :P 

thanks

**Comment by revilheart** [comment]
Did something different: all elements except for the group button and the avatar are faded out now. Let me know if it's still not pleasant.

**Comment by ldeman** [comment]
looks like the opposite to me.. they're all faded regardless if hovered or not, just not as bad on the fading.

**Comment by revilheart** [comment]
Hovering doesn't change opacity anymore, because the group button and avatars are not faded out.

**Comment by ldeman** [comment]
hmm, well tbh it still looks like crap for me.  
![peek 2017-02-24 06-34](https://cloud.githubusercontent.com/assets/10275898/23303751/8375222e-fa5b-11e6-8711-c7a33e07e389.gif)

even no dark theme still doesn't look any better imo.
![screenshot from 2017-02-24 06-36-58](https://cloud.githubusercontent.com/assets/10275898/23303788/b6df747a-fa5b-11e6-9b85-d3009f4e5dcd.png)

**Comment by revilheart** [comment]
Do you have "Fade out entered giveaways." enabled in Comment Tracker?

**Comment by ldeman** [comment]
no

**Comment by revilheart** [comment]
Actually it looks like nothing really changed for you. Do you have the latest update? It's working fine here, even with dark theme.

**Comment by ldeman** [comment]
4.7.3 & No Updates found.

**Comment by revilheart** [comment]
Can you see if the giveaway element has a class called "rhFaded"? And if it does, could it be a conflict with some other script?

**Comment by ldeman** [comment]
![screenshot from 2017-02-24 06-58-51](https://cloud.githubusercontent.com/assets/10275898/23304307/be242804-fa5e-11e6-8aaa-43e9ee9f85ec.png)

it does, and just tested with all other scripts disabled and it still happens.

**Comment by revilheart** [comment]
I think [Nyx](https://www.steamgifts.com/go/comment/ExExUtX) was having the same problem as you. They just said they updated and it stopped doing it, but the fact that you have the latest update baffles me.

**Comment by ldeman** [comment]
yeah i have no idea.  i wonder if the next update will autofix it for me or something like that.

**Comment by revilheart** [comment]
Pushed it, let me know.

**Comment by ldeman** [comment]
still happening on 4.7.4 also.

**Comment by revilheart** [comment]
Does it happen if you disable Comment Tracker?

**Comment by ldeman** [comment]
yes,  tried disabling both group popout and comment tracker entirely and only tested the avatar side and it's still faded on entered GAs.

**Comment by revilheart** [comment]
This doesn't make any sense. Can you instead of searching for the class "rhFaded" on the entire page, do it only on the giveaway element? Like this:

![](http://i.imgur.com/PKlhypt.png)

**Comment by ldeman** [comment]
i honestly don't understand element searching at all, sorry.

**Comment by revilheart** [comment]
Just right click on the giveaway and go to "Inspect Element".

**Comment by ldeman** [comment]
which part of the giveaway would you like me to inspect?  if i click the title it takes me to one section for screenshot, if i click the avatar it takes me to a different, etc..

**Comment by revilheart** [comment]
If you click on the title, the class should be about 4 elements above.

**Comment by ldeman** [comment]
i think this maybe what you want a shot of? 
![screenshot from 2017-02-24 08-49-13](https://cloud.githubusercontent.com/assets/10275898/23307735/331d1666-fa6e-11e6-914a-a908a63291a1.png)

**Comment by revilheart** [comment]
A bit more up.

**Comment by ldeman** [comment]
sorry, this it?  
![screenshot from 2017-02-24 08-52-21](https://cloud.githubusercontent.com/assets/10275898/23307838/9c42055c-fa6e-11e6-954c-0594e50ac8dc.png)

**Comment by revilheart** [comment]
There you go, it's using "is-faded" instead of "rhFaded". I'll try to figure out why.

**Comment by ldeman** [comment]
ahh, yeah.  now i see why i had a hard time finding it.  i was looking for that rhFaded to be there.  ^^
i've familiarized myself with inspecting a little more, hopefully i won't be quite the noob if i need to do stuff like that again. xD

sounds good though.

**Comment by revilheart** [comment]
Fixed with v4.9.1?

**Comment by ldeman** [comment]
no on 4.9.2 (missed 4.9.1 while asleep).  sorry.

**Comment by ldeman** [comment]
ahh, just realized.. it works fine if i enable the enter button though, but i don't like the enter button on the page.  i only tested that due to what squished said in the topic.  odd he confirmed its fixed though and its not for me.

**Comment by ldeman** [comment]
just thought to retest what the inspection says, and it's claiming i'm on rhFaded now with the settings i prefer (no GA enter button), but still fading it anyways for me.

![image](https://cloud.githubusercontent.com/assets/10275898/23331197/0338fc80-fb27-11e6-87d6-ee304977ea2d.png)

**Comment by revilheart** [comment]
Oh I got it. It really is a problem that happens when Enter Giveaway Button is disabled. I'll fix it in the next version.

**Comment by ldeman** [comment]
sounds great, thanks. ^^

**Comment by revilheart** [comment]
Should be fixed. ^^

**Comment by ldeman** [comment]
is indeed!   thank you very much!  xD
