### ISSUE TITLE
[Bug] Comment History Disable doesn't disable inside settings.

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#11]
title ^   xD

**Comment by ldeman** [comment]
well it at least doesn't disable the history button inside the settings.

**Comment by ldeman** [comment]
woahhhhh.... but it seems to of killed all of my tracking.  now i've never visited anything before.  =(

**Comment by revilheart** [comment]
Buttons on settings menu are shown regardless of whether the features are enabled or not, I'll change that later.

What, it erased your Comment Tracker data? o.O Just randomly or after you disabled it?

**Comment by ldeman** [comment]
yeah, but i cannot seem to replicate the issue again.  i've been trying over and over.. i wouldn't mind that wipe afterall, but didn't think about it too much before i removed the export it did prior to import. lol.

**Comment by ldeman** [comment]
it was certainly after the disable, but idk if it was related or just random after the disable.  i didn't notice for a couple mins.

**Comment by revilheart** [comment]
Maybe it only works the first time you disable, I'll install the script prior to the Comment History version on a separate browser and do some testing.

**Comment by revilheart** [comment]
Yeah, can't reproduce it either. If you compare the two export files on notepad, one just completely vanished with "Comments"?

**Comment by ldeman** [comment]
unfortunately i didn't think to keep the data, wish i had, i'd actually go back to it if i had.  not in trash can either, i did a perm delete :S

**Comment by ldeman** [comment]
but i'm going thru now and marking stuff as read.. i'm wondering if maybe i didn't hit a max cache wall on it and instead of erroring it just resat.

**Comment by ldeman** [comment]
yeah i just cannot seem to replicate it either.  sorry i deleted that data fluke :/   i won't jump the gun to try and fix that and remove the data if there ever is a next time.

**Comment by revilheart** [comment]
Ah too bad, hopefully it doesn't affect someone else. I don't think there's such a thing as a cache limit.

**Comment by revilheart** [comment]
Found the source of the bug, it's not related to Comment History: if you visit SteamTrades it will replace SG's comment tracker data with ST. Will fix it in the next version. I assume you visited ST before your data was wiped?

**Comment by ldeman** [comment]
no, looks like last time i visited steamtrades was feb 20th according to history.  additionally it only seemed to of wiped the comment tracker stuff instead of everything.  i know i changed a few settings on accident when i was trying to turn off the discussion history though.  i accidentally turned of username history for a few seconds then quickly re-clicked it after i realized i clicked the wrong thing.

could there be something about turning stuff on and off too fast?  maybe it was saving the change to disable and while it was still saving that change i re-enabled it too fast and it caused it maybe?

**Comment by revilheart** [comment]
Changing settings shouldn't affect anything, they are saved separately. The only issue I found that could have wiped the data was the bug I fixed in v4.9.5, which was overwriting SG data with ST.

**Comment by ldeman** [comment]
you know what, screw what my history says, i remb doing so now... i went to one of my bookmarked old trades where i store ascii/unicode stuff.  that was indeed it.

**Comment by revilheart** [comment]
Ah glad to know that. :)

**Comment by ldeman** [comment]
yeah, finally found it in history too (idk why it didn't show up under trades search)
![image](https://cloud.githubusercontent.com/assets/10275898/23340459/4f23af98-fbfc-11e6-9939-017d8aeab085.png)
![image](https://cloud.githubusercontent.com/assets/10275898/23340462/55031dea-fbfc-11e6-89ae-e6b84569c926.png)

**Comment by revilheart** [comment]
Revamped the settings menu and this shouldn't be a problem anymore.

**Comment by ldeman** [comment]
yeah, closing now.  thank you much!  =)
