### ISSUE TITLE
[Feature Request] Groups Shared Button from User Profile

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#12]
I just thought of a great alternative to running around and tagging users groups that I think many would utilize.  basically a button somewhere on the users profile header (preferred there so it can work thru avatar popout) that when you click it, it lists shared steam groups.

scrollable style list similar to the group popout on mainpage would work beautifully imo but it could even be like the manage lists in the settings instead, either way.  additionally it could be either steamgifts synced shared groups, or steamcommunity shared groups.  those decisions ofc are upto you, but i think the feature would be nice just as long as it gives me a rough idea however its done.  ^^

**Comment by revilheart** [comment]
I don't think it can be done through SteamGifts since you can only see the list of groups that you're in, not other users'. I'll check through SteamCommunity.

**Comment by ldeman** [comment]
sounds good.  thanks

**Comment by revilheart** [comment]
Added

**Comment by ldeman** [comment]
awesome thank you.  it's working great!  ^^

(except with avatar popout in dark theme, but that's probably a squished thing to deal with)
