### ISSUE TITLE
[Bug]  Username history error from avatar popout

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#13]
Seems to do it on all users too, not just the user in screenshot. 
![image](https://cloud.githubusercontent.com/assets/10275898/23341121/62b3f508-fc07-11e6-80b9-2a96a710e667.png)

edit: correction, it's not just from the avatar popout.. it's also doing that from user profile pages.

**Comment by revilheart** [comment]
Should be fixed.

**Comment by ldeman** [comment]
seems so, thanks. ^^
