### ISSUE TITLE
Bugged user info in giveaways

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#14]
Hello dude,
I just found out that the user info in giveaways is bugged. The icons are red and half transparent. I disabled all the other scripts to be sure it is not a conflict but it was the same. The info works good in the other places, just in giveaways is bugged. (Pilda)

[Screenshot](http://i.imgur.com/UFfKD9u.png)

**Comment by revilheart** [comment]
It's not bugged, it's because the avatars in giveaways are transparent. I'll see if I can add a background to it in the next version.

**Comment by revilheart** [comment]
Changed it.

**Comment by gizellos** [comment]
It works, thanks.
