### ISSUE TITLE
# 17 [BUG]Winning chance do not take multiple copies into account

### ISSUE THREAD

**Issue by to-dr** [revilheart/rhSGST#17]
# [BUG] as in title :P

**Comment by revilheart** [comment]
It does though.

**Comment by to-dr** [comment]
me be bad with math lol? 💃 
![](http://i.imgur.com/IVpHU2b.png)

**Comment by to-dr** [comment]
I don't know how exactly sg system works though, maybe it is like 114:1 for first gift, than 113:1 for second etc?

**Comment by ldeman** [comment]
yeah, shouldn't that be 114:20 then though?
or 5.7:1?

**Comment by to-dr** [comment]
d3man: I think I wrote it in red on prtscrn :D

**Comment by ldeman** [comment]
yeah, i think any of those would be more accurate.

(114/20):1
or
114:20
or
5.7:1

^^

**Comment by revilheart** [comment]
It should be 6:1. Does this also happen from the main giveaways pages?

**Comment by revilheart** [comment]
Fixed
