### ISSUE TITLE
Issue about Enter / Leave Giveaway Button

### ISSUE THREAD

**Issue by leona-eve** [revilheart/rhSGST#18]
I want to give some suggestions about the "Enter / Leave Giveaway Button". Assuming I have 20 points now and I like to enter a GA required 15 points. After I click the "enter button", the button becomes "Not Enough Points" instead of "Leave". If I have enough points and enter a GA successfully, it should become "Leave". (this should be fixed, too) And once it becomes "Not Enough Points", there is nothing I can do but refresh that page, wait the points refresher (if enabled) or open the GA page. I suggest you could let the "Not Enough Points" become a button and when the user clicks it, it becomes "Enter" again and the user could try to enter that GA again without doing other actions or wait.

**Comment by revilheart** [comment]
Fixed and changed the way the "Not Enough Points" button is shown.
