### ISSUE TITLE
Issue about Giveaway Description / Comment Box Popup

### ISSUE THREAD

**Issue by leona-eve** [revilheart/rhSGST#19]
1.Giveaway Description / Comment Box Popup
　1.1Pop up when entering a giveaway if Enter / Leave Giveaway Button is enabled.

This function is broken. If you only enable 1 but not 1.1, it's not working.

**Comment by leona-eve** [comment]
update:
I found that if the creator didn't leave a comment when he create a GA, it's not working. Otherwise it could be popup successfully as before.

**Comment by revilheart** [comment]
Fixed
