### ISSUE TITLE
question

### ISSUE THREAD

**Issue by to-dr** [revilheart/rhSGST#2]
not really issue, sorry if dumb q - does not received also works for GAs won?

**Comment by revilheart** [comment]
Nope, only for user profiles and giveaway winners.

**Comment by to-dr** [comment]
hmm, probably I did not phrase my question correctly :) 
Is there possibility to check if some user marked any of his won GAs as not received? (atm I see only for those sent). The reason I am asking is in past, I have found that way that user changed one of multiple wins to non received so he can pass sgtools (I could check, because I had a ticket for that). Now I suspect another person for that, but with 500+ wins and shitty internet for a while it is not easy,,, :)

**Comment by revilheart** [comment]
I see. Not at the moment, but I can add that. :)

**Comment by to-dr** [comment]
thanks! closing than as it was _dully_ noted :)
REally appreciate all your work!
