### ISSUE TITLE
[Enhancement] Better order of GA icons

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#20]
Hi, I think (more precisely I feel) that icons that are always there, should be always at the same place. Then it is much better to find them for eyes.  It also looks better arranged. It helps to identify each GA faster.

Enter icon is always there, is most important and it is distinct , so I would put it to the most right place.
Comment and chance to win are always there to, so I would put them to the left  of the enter icon.
The other icons are not always there si I would put the to the left of all if the icons that are always there.

I made a photomontage where you can see what I mean and what it looks like. I think it looks better, what do you think?

![razeni info o ga](https://cloud.githubusercontent.com/assets/2397851/23464220/90790a48-fe94-11e6-94c7-3a5e27a649b0.png)

**Comment by ldeman** [comment]
i don't even use the enter button feature, but that does logically make sense to me a bit more too.. since the enter button is the most static button it mine as well be in a the most static location.

**Comment by ldeman** [comment]
@revilheart nice ^^

@gizellos i wasn't meaning anything bad about the button, i'd most likely use it if i wasn't in a group with strict rules on what i can and cannot enter though. i'm already fairly bad about misreading stuff as it is, so its best for me to open each and every page up to read them over more carefully and make sure. 

&&& how did you change the topic title.. i've wanted to do that on 1-2x of my old tickets.. xD lol

**Comment by gizellos** [comment]
ldeman:
dude, the feature in this script is so advanced that you can set it that it will show you the description if there is one. So your problem is solved. :)

**Comment by ldeman** [comment]
i know, i just misread stuff so easily i prefer opening up several tabs of games i have interest in and then going thru reading them one by one slowly.  ^^

**Comment by revilheart** [comment]
Done

**Comment by gizellos** [comment]
Nice, it looks very good. Thanks a lot. :)
