### ISSUE TITLE
[Enhancement] refresh statuses of GAs after sending keys

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#21]
When I send keys to winners via the "Sent unsent gifts" feature, the webpage didn't change the status of the ended giveaways so it says the keys are not send (until I refresh the page, of course). Could you actualize the statuses after the sending finish? I mean to replace unsent with send.
![2017-03-01_163832](https://cloud.githubusercontent.com/assets/2397851/23467374/242ed08e-fe9e-11e6-87e9-c811f9152b02.png)

**Comment by revilheart** [comment]
Done
