### ISSUE TITLE
[Feature request] WL/BL graph - switch between WL only, BL only and both

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#23]
On the page [My stats](https://www.steamgifts.com/stats/personal/community), there are the info about the number of being whitelisted and whitelisted together with a nice graph.

I don't want to see the amount of blacklists so I removed the elements via adblock. It works well, but the problem is, that the graph contains both - whitelists and blacklists and when I removed it, I can't see also the whitelists even if I would like to see them.

It would be nice if there were switches between WL only, BL only and both, near the info and the graph. The switches would switch between both, the number and the graph.

An important thing would be to save the settings so that it wouldn't reset to both (both would be the default option, of course).

Edit: or there could be just an opinion in settings who would hide the number of BL and removed the BLs from the graph.

(My life on SG is much more pleasant since I removed the BL information.)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Thanks a lot. Just please fix this in the graph (I enabled the blocking blacklists).

![2017-03-03_195329](https://cloud.githubusercontent.com/assets/2397851/23564713/4e8cb6c6-004b-11e7-89a1-f7dd210a7ad0.png)

**Comment by revilheart** [comment]
Hm I don't know why that's happening to you, there's nothing here.

**Comment by gizellos** [comment]
The script blocked the blacklist number and blacklist graph as I chose in the settings but it didn't removed the number of blacklists  in the graph when I hover there... Please remove it too.

**Comment by revilheart** [comment]
Oh I see what you mean now, thanks for explaining.

**Comment by gizellos** [comment]
Hehe. Thanks again. :)
