### ISSUE TITLE
[Enhancement] Highlight discussion from its post

### ISSUE THREAD

**Issue by SnowyK** [revilheart/rhSGST#24]
Currently there's the feature to highlight / star a discussion post on the https://www.steamgifts.com/discussions page but sometimes you get linked to a discussion post from elsewhere and there's no way to directly highlight the thread from within the post itself. It'd be nice to also get an icon or option somewhere to star the discussion from the thread's main post/page.

**Comment by gizellos** [comment]
Totally agree, I already asked for this.  And it would be also good to have the possibility to mark the post as read inside the post since it can be late to do that then from the list.

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Thanks.
