### ISSUE TITLE
[Bug]  Not enough points leaking thru, when enter button feature is even turned off

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#25]
![image](https://cloud.githubusercontent.com/assets/10275898/23504609/f4a68916-ff05-11e6-9f43-2dd28585dd77.png)

enter button is disabled entirely for me, yet i still see "Not enough points" on my own profile pages GAs.  lol ^^

**Comment by gizellos** [comment]
I can see even the enter buttons on my profile page (though, I don't know which feature you mean).

**Comment by ldeman** [comment]
@gizellos yeah but my enter button is disabled.
![image](https://cloud.githubusercontent.com/assets/10275898/23511025/6af92c34-ff21-11e6-940d-c63a022721f7.png)

**Comment by gizellos** [comment]
Oh, I see. I have this enabled, so I found another bug while thinking about your issue because both "Not enough points" and "enter" stuff should not be there no matter if an option is enabled or not since you cannot enter your own giveaway.

**Comment by ldeman** [comment]
yeah i agree, the enter button feature probably just needs a restriction to even work on your own profile page at all and i think all problems are solved.  i don't believe that shows up anywhere else, but then again i'm rarely out of points to notice.

**Comment by revilheart** [comment]
I think I know what might be causing it. Do you have Points Refresher enabled?

**Comment by gizellos** [comment]
Another bug with the enter button. I can see both, enter button and Not enough points message. I have the refresher enabled.

![2017-03-02_173229](https://cloud.githubusercontent.com/assets/2397851/23516735/63e9d694-ff6e-11e6-9b04-9b592bc530d5.png)

**Comment by ldeman** [comment]
@revilheart no, it's disabled.  this shot with the last shot i think covers all my settings. =)
![image](https://cloud.githubusercontent.com/assets/10275898/23517168/399be06e-ff35-11e6-8510-e044b4415c49.png)

**Comment by revilheart** [comment]
@gizellos That's supposed to happen if you don't have enough points. Someone requested it to be that way because they wanted to try to enter again without having to refresh the page or wait for Points Refresher.

**Comment by gizellos** [comment]
@revilheart Aha, I see. Then it would be good if the script would enter the GA automatically when the user has points for it. The GA would add to a queue and the script would enter them one by one. I am not sure when this would be the so-called "the bad auto joiner", though.

**Comment by revilheart** [comment]
Fixed

**Comment by revilheart** [comment]
@gizellos Yeah, I don't like that automatic idea. I'll an option to disable it in the next version.

**Comment by ldeman** [comment]
gonna assume it is, but currently with the monthly just releasing the points are coming in to fast to really test for someone like me with 4600+ games owned.  ^^

thank you again. xD
