### ISSUE TITLE
[Feature request] Notify about received keys from won GAs

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#26]
If I win a GA, icon with number appears - that's fine. But there is not an indicator that the giveaway creator already sent the key for the game so I have to go to the won GA page again and again and that's quite annoying.

Could the script notify us if the GA creator of a won giveaway already sent the key to me? Maybe the color of the cup could change it's color?

![sent keys](https://cloud.githubusercontent.com/assets/2397851/23526735/704fb2ee-ff93-11e6-9002-f4384f13114c.png)

**Comment by revilheart** [comment]
Added

**Comment by gizellos** [comment]
Wow, this will be really handy. Thanks for it. :)

**Comment by gizellos** [comment]
I can confirm that it works like a charm. :)

![sent keys](https://cloud.githubusercontent.com/assets/2397851/23579849/44ce8640-00f6-11e7-938e-b5aec20f0c7b.png)
