### ISSUE TITLE
[Feature request] remove from already won giveaways

### ISSUE THREAD

**Issue by 123top** [revilheart/rhSGST#29]
Can you add a button that removes all your entries from already won giveaways (giveaways from games you already own/won)?

**Comment by ldeman** [comment]
sg relative comment https://www.steamgifts.com/go/comment/un1nPxf   ;)

but leave this ticket up as a reminder / easier for him to keep track of.  xD

**Comment by ldeman** [comment]
this one won't need to be done.. CG is doing it directly on the site finally!!!!! ^^
https://www.steamgifts.com/go/comment/c7WpO1N

**Comment by revilheart** [comment]
Great news!
