### ISSUE TITLE
D3M4Ns Inevitable Requests/Bug Reports

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#3]
First off, Thank you for the amazing updates ^^

i'm honestly not sure how these "issues" work" so just creating it like this and hoping to continue to comment on a single "issue report" rather then open up a new topic each and every time.

would it by chance be to much trouble to get the thread marking as read button to work with all pages?  i honestly can't stand endless scrolling and don't wan't to have to enable it each time a thread gets bumped that i've already read before in order to easily mark all 12 pages read.

**Comment by ldeman** [comment]
also, any chance you can reverse the order on the real cv sgtool sent/won links?  (or add option to)

instead of http://www.sgtools.info/sent/d3m4n it goes to http://www.sgtools.info/sent/d3m4n/newestfirst

**Comment by revilheart** [comment]
I think it works like one new topic per issue. It's easier to track what's already been added / fixed that way. :)

Added the option to mark all comments of a discussion as read from the discussions page, and also a count that shows how many comments were added since the last time.

**Comment by revilheart** [comment]
And added the reverse order functionality.

**Comment by ldeman** [comment]
okay, yeah i saw that after i created this one.. now that i made this one i understand how it works a lot better.

anyways, thanks a ton for the new features, and the reverse order i see u just typed up.  (love the auto-load of messages here btw)  xD
