### ISSUE TITLE
[Enhancement] rhSGST button with menu

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#31]
I believe that rhSGST already deserves its own button with menu (somethink like the buttons Giveaways, Discussions, Support or Help). Some of the great features would be more accessible thanks to it. There could be links or buttons to features, link to the changelog, link to github, quick settings, and so on. 

Some of things that could be there are these:

- Manage data
- Comment history (!)
- WL/BL manager
- changelog
- links to github and SG page
- buttons for synchronisation features

I am not sure what settings would be useful in the quick settings, though. Let's think about possibilities.

**Comment by revilheart** [comment]
Added a simple version of it. Not sure about adding too much links for managing data and changelog, 5 links already feels like too much.

**Comment by gizellos** [comment]
Nice, thanks. Looks good. :)

**Comment by ldeman** [comment]
i like the button, but any chance it could be made to where it doesn't resize and move the other buttons?

upon pageload, if i try and click discussions b4 the button has fully appeared it slides discussions to the left and i end up clicking on support instead.  i'd prefer it if none of the original buttons were resized or moved, but the button still appeared there after the page has fully loaded.  maybe take advantage of the fairly large gap between "Help" & "Giveaways Created" without being directly up against the other buttons?

**Comment by revilheart** [comment]
@ldeman Everything seems to be working fine here, can you illustrate it in a GIF maybe?

**Comment by ldeman** [comment]
![peek 2017-03-04 07-55](https://cloud.githubusercontent.com/assets/10275898/23579306/275c516e-00b0-11e7-963b-d06e1a8a7068.gif)

it's hard to deliberately screw up on click, lol.. but it happened a few times on accident naturally.  ^^

**Comment by gizellos** [comment]
Do you mean the moving buttons? Yes, I have it too. I don't know why it happens, hopefully revil will know.

**Comment by revilheart** [comment]
Oh is it related to the dark theme?

**Comment by ldeman** [comment]
yeah seems so.  it doesn't shift, resize, or move anything when dark theme is disabled.

**Comment by gizellos** [comment]
I think it doesn't, I don't use the theme. But if you disable the whole script - it does it too, so it seems to be not related with rhSGST.
![no scroll](https://cloud.githubusercontent.com/assets/2397851/23579726/f5fa55b4-00f3-11e7-8972-bd278844a65f.gif)
