### ISSUE TITLE
[Enhancement] Make sections in the settings

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#32]
Well,
since the settings is so big now, it is quite hard to search anything there. I suggest to make some logical sections in the settings, such as Giveaways, Discussion, General, Other, and so on. The section could be divided just by headings.

**Comment by ldeman** [comment]
i honestly didn't even follow what the request meant, but wow that really does look much better and now i do understand what the request was.  ^^

thanks!

**Comment by gizellos** [comment]
Good work as always. Thanks. :)

**Comment by revilheart** [comment]
You're welcome, thanks for the suggestion, that looks much better indeed. :)
