### ISSUE TITLE
[Feature request] Show ratio in user profiles

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#34]
I already asked about this on the forum, but here it is more visible. I would like to see ratio in user profiles. Just simple Gift Send / Gift Won would be enough. If you think some other ratios would be useful, you can add there too.

![ratio](https://cloud.githubusercontent.com/assets/2397851/23581235/bea02d2e-0110-11e7-9f62-e2551a144051.png)

**Comment by revilheart** [comment]
Hmm just noticing from this that Shared Groups Checker is showing up in your own profile when it shouldn't. :P

**Comment by gizellos** [comment]
Thanks a bunch.
