### ISSUE TITLE
[Bug] Mark thread as read not working

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#36]
for some reason it just isn't working for me today.  and i actually did test it without dark theme first for a change.  ^^ hehe
![peek 2017-03-05 07-48](https://cloud.githubusercontent.com/assets/10275898/23587752/7cf6d284-0178-11e7-8d4d-3fa77fd51a58.gif)

no errors in console either.

**Comment by gizellos** [comment]
It works, just the number in the brackets is not refreshing.

BTW I am not sure you did you mean that with the dark theme. The gif of yours is discotheque as always. :D

**Comment by ldeman** [comment]
even waiting 5mins later then refreshing they still show up unread for me, and yea the gif is with dark theme enabled, but i additionally tested without it before i made this issue ticket. ^^

**Comment by gizellos** [comment]
For me, refresh helps it. It is strange. Either way it is a new bug.

**Comment by ldeman** [comment]
yeah, i see now what you mean too.  i think my wl/bl update was causing it not to work at all until i restarted my pc.. now it's just not getting the busy icon indicator to tell me when it's done.

**Comment by revilheart** [comment]
It was clearing out the progress status. Fixed.
