### ISSUE TITLE
[Enhancement] Set padding to the group list cells

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#37]
Please set some padding to the group list cells. The group's names are too close to the right side of the cells.

![2017-03-05_164133](https://cloud.githubusercontent.com/assets/2397851/23588857/fe789d7e-01c3-11e7-91d6-9b7c39cfc4b9.png)

**Comment by gizellos** [comment]
Looks good, thanks. BTW didn't you make the group list smaller few days ago?  Its high is too low. I hate scrollbars. :-(:.  Maybe you could set the high according to the user's screen resolution. Its high now is really too low for full HD resolution and it this resolution is most popular now.

**Comment by revilheart** [comment]
I'll change width and height of some elements to percentages so that they are adjusted based on the user's screen in the next version.

**Comment by gizellos** [comment]
Looks good now, thanks.
