### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#4]
5x "Wait"'s & 10mins later here we are..  i'm fairly patient, but... i'm also fairly confident it's not going to go.

![screenshot from 2017-02-21 09-21-01](https://cloud.githubusercontent.com/assets/10275898/23171165/5b1cd178-f817-11e6-857d-97bd399e75b9.png)

**Comment by ldeman** [comment]
yep.. fail. 
![screenshot from 2017-02-21 09-25-10](https://cloud.githubusercontent.com/assets/10275898/23171298/b62f9d66-f817-11e6-923d-43507b909a9d.png)

**Comment by revilheart** [comment]
It got stuck on Steam groups? That should be scanned quite fast. Can you try syncing from the settings menu and seeing if the same happens?

**Comment by ldeman** [comment]
yes it happens there too, exact same thing. and when tampermonkey crashes it does not seem to want to come back until i restart my computer.  even loging out of my x session and logging back in won't allow for tampermonkey to start working again.

i think it's all due to my cache being large. i still get error code on my "wl/bl manage".

also another thing i realized with the "wait for free slot" queing on the discussions page to mark threads read, there is no limit to how many you can que up.  if i exceed a que limit of 3 (3 is fine), i'm guaranteed to cause tampermonkey to crash.  i know the limit after testing it a few times for my hardware, but you may want to add a limit in there so others don't try and exceed it and cause problems for themselves as well.  now that i know the limit i'm fine without it, but just wanted to let you know.

**Comment by revilheart** [comment]
Are you in a lot of groups?

Does the browser also crash if you queue more than 3 in different tabs? I'll work on a queue limiter for the same page, but not sure I can do it for multiple tabs.

**Comment by ldeman** [comment]
53 groups, it never had sync issues prior to the 4.x+

i'll see if i can't watch the console before it all crashes during another test. and honestly no idea on multiple tabs limit. that was just single tab test with only a discussion sitting in the bg that hadn't been looked at or touched.  i'll test it out a little with that too.

**Comment by revilheart** [comment]
That doesn't look like a number that could cause problems. Maybe the crash happens during whitelist / blacklist but freezes while the message shows Steam groups. Thank you for taking the time to test it though, and sorry this is happening to you.

**Comment by ldeman** [comment]
yeah that makes sense since it has errors when trying to manage it. 
![image](https://cloud.githubusercontent.com/assets/10275898/23180700/dc9b0fa6-f837-11e6-87a8-0bef38d121b8.png)

**Comment by ldeman** [comment]
further tests show nothing in the console for the sync issue, and absolutely no attempts to request groups from steamgifts while watching thru the network monitor.  it must be related to the wl/bl cache being to large (but not really all that large considering i've gifted almost 3k games).

**Comment by revilheart** [comment]
Stack size exceeded is often caused by recursive functions (functions that call themselves over and over again). And this script is filled with recursive functions because it needs to wait until a content is requested to continue to the next call. That's most likely what's causing this issue, because it stacks the functions and then there's no more room in the memory to keep stacking them if the data is too large. I have an idea on how to replace that recursion and will implement it later.

**Comment by ldeman** [comment]
okay sounds good

**Comment by revilheart** [comment]
Try loading your WL/BL cache with v4.2.6. It shouldn't have any problems now. Not sure if it also fixes syncing, let me know.

**Comment by ldeman** [comment]
YES!!!! thank you, it fixed both of those issues.  syncing works once again. ^^

also that method of retrieval looks & feels much more stable with the progress showing.  xD

**Comment by revilheart** [comment]
Glad to hear that. xD
