### ISSUE TITLE
[Bug] Unknown Error (but it's effecting the time display feature)

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#41]
specifically my own profile, not everyones.

![image](https://cloud.githubusercontent.com/assets/10275898/23593333/3a5a170a-01d3-11e7-9c58-3c0778ab7fd5.png)

tested with all other scripts disabled

**Comment by ldeman** [comment]
it might have something to do with this...
![image](https://cloud.githubusercontent.com/assets/10275898/23593559/0c933376-01d6-11e7-835b-cb7e8c62d75b.png)
it looks like it's trying to get winning chances of my own invite only giveaway, and it clearly cannot.

**Comment by revilheart** [comment]
Fixed. Kind of silly for SG to show your private giveaways as "Invite Only" on your own profile if you ask me. :P
