### ISSUE TITLE
[BUG] Template End Time Saving Issues

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#42]
the last few times i use the templates it doesn't seem to store the time or amount of minutes properly.

specifically if i set the end time to 12:00pm for 2days from whenever i start it, save template and start giveaway, then go on to the next and load that saved template, it loads it up for 12:00am end time instead (or a minute or two after if i'm not fast).

not sure if it's intended to go by precise minutes or by the precise set end time, but either way it isn't saving noon/midnight correctly.

**Comment by revilheart** [comment]
Fixed the noon bug.

As for the end time, if I understand your question, the template saves only the duration of the giveaway, not the exact end time. So if you save a template for a giveaway that lasts 2 days and ends on 2pm,  and then apply that template on 3pm, the end time will be 3pm, not 2pm.

**Comment by ldeman** [comment]
okay, that still works for me.  i only use it for "temp" templates, so i usually just have to adjust it by a minute or two so they all end at the same time anyways.  just the noon bug that was annoying me since 11am or 12pm were my normal end times i shoot for on group GAs.  ^^

thank you very much for all the bug fixes!  ^^
