### ISSUE TITLE
[Feature request] Winner Comment Highlighter

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#43]
i've been thinking about this one a while and am just not sure if it can be done in a way where it doesn't significantly impact page loads, however tossing it out there in case you can think of a way where it doesn't impact performance.

basically do you think when i goto www.steamgifts.com/messages there could be a feature that sees if the person that is messaging me is also the person that had marked the giveaway "received" on the /winner page, if they are speaking to me on a giveaway page?   or anything other relative way of knowing that the person that is talking to me on a giveaway is the actual winner without going thru 3x manual page loads (permalink from /messages to the GA, /winners tab to insure they are or are not the winner, then finally back to the comment section to reply)

edit:
reason it's so annoying for me is cause i reply to winners thank yous, but ignore most all other generic thank yous for entry.  (unless they say something funny worthy of replying, or additionally wish me a good weekend or something worth replying too)

**Comment by revilheart** [comment]
There is a way that wouldn't impact page loads: if you sent the gifts to the winner using Unsent Gifts Sender, I could save the winners in the storage and that way it would be very easy to highlight them on the messages page without having to request anything. I could also go a bit further and just save every single user on the winners page of a giveaway when you visit it for users that don't use Unsent Gifts Sender.

**Comment by ldeman** [comment]
the unsent gift sender wouldn't work for me, only approx 1/5 of my stuff gets sent thru it.  but just storing all the winners at the time i press the send button i think could work.  i say at the time i press send though just in case i press the request reroll button instead.  :D

**Comment by ldeman** [comment]
but... it would need to check if they are talking to me on the giveaway page still too. i don't want all 2-3k of the different winners to be highlighted everywhere i talk to them.  xD

**Comment by ldeman** [comment]
that george example in the above edited comment is why i was thinking maybe just have it run a scan on only the unmarked as read (official SG marking) comments on the /messages page and if the comment is on a /giveaway page then check /winners to see if it's a match.  i think that's the only way to have the least amount of requests yet only highlight the users that are commenting directly on their won giveaways only.

**Comment by revilheart** [comment]
I think the feature covered all your concerns.

**Comment by ldeman** [comment]
awesome, thank you again!  =)

**Comment by gizellos** [comment]
Good idea, thanks to both of you, guys.

**Comment by ldeman** [comment]
ahh, thanks again on this one.. it's such a time saver, even only a small time saver per time.. but as many "thank yous" as i get and manually checking to see if each and every one of them were a winner was a PITA!   xD
