### ISSUE TITLE
[Bug] Chance to win - wrong result

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#45]
Hi, I just noticed that there is a problem with the chance to win value in the pinned GA. Normal GAs seems to work normally.

![2017-03-07_155004](https://cloud.githubusercontent.com/assets/2397851/23661857/196d5a26-034e-11e7-8db1-3e665bfdc1ef.png)

Edit: another GA with just 50 copies works normally. Maybe it is just with many copies.

**Comment by revilheart** [comment]
It's probably the comma in 2,000. I thought I added a way for the script to get 2000 instead of 2, but maybe I overlooked something. Will check it out.
