### ISSUE TITLE
[Bug] Remove entry links in entered giveaways are not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#47]
When I am on Entered giveaways page and I click on remove a link, nothing happen. The link is still there unchanged and the entry is not removed. There are no errors in the Console.

**Comment by revilheart** [comment]
What entry links?

**Comment by gizellos** [comment]
![2017-03-08_153514](https://cloud.githubusercontent.com/assets/2397851/23708036/da450cc8-0414-11e7-850d-3b51d2b99f15.png)

**Comment by revilheart** [comment]
Weird, the script should have no effect on that link. Maybe it's because of Giveaway Winning Chance inserting a column there? Have you tried with it disabled?

**Comment by gizellos** [comment]
It is the same with disabled GA chance. I tried to disable all others scripts to be sure it is not just and interfering of scripts but it was not. Without rhSGST it works normally.

There is just an error that is not caused a script (I have it there even with all scripts disabled). I am not sure if it could be the problem.
![2017-03-08_154256](https://cloud.githubusercontent.com/assets/2397851/23708415/1abfba2c-0416-11e7-916c-4a02786a20cc.png)

**Comment by revilheart** [comment]
That looks like a bug from a Chrome extension. Can you try disabling your extensions and trying again?

**Comment by revilheart** [comment]
More specifically, it looks like that extension is called Tab Position Options.

**Comment by gizellos** [comment]
Yes it was an error from an extension but the issue is still there even if I disable all the extensions.

But I think I found the problem. It is endless scrolling. With it disabled, it works normally.

**Comment by revilheart** [comment]
Oh you didn't mention it only happens from page 2 onwards. That explains it, event handlers aren't attached to dynamically generated content, so I have to attach them manually (the same thing happened to the hide giveaway button in the main page). I'll fix it in the next version.

**Comment by gizellos** [comment]
Oh, I didn't realize that. Yes, you are right, I tried it from the end. :) Nice you know where the problem is.
