### ISSUE TITLE
[Feature request] remove entries for owned games

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#49]
Cg just announced that [SG started to remove entries for won games](https://www.steamgifts.com/discussion/P3Zcz/automatically-removing-entries-after-a-win) and that's nice but it would be good to have the possibility to remove entries for owned games as well (since we also can get games outside sg). It could be a button in the entered giveaway section.

**Comment by ldeman** [comment]
+1

at the very minimum if large library scan/removal is an issue (would be best, but if it's too much), have a button that can read chart descriptions and then remove the associated appid's from giveaways entries.  single purchase games/apps would still have to be removed manually, but at least when you buy a bundle you could go to the thread associated with it and remove the entries that way.

**Comment by gizellos** [comment]
I think the detection should not be a problem. For examle, SG game tags script can detect owned games and it works very well, so to use the same approach and to use it for the feature.

**Comment by ldeman** [comment]
the removal request of my 4,000 owned games my be an issue though.

**Comment by gizellos** [comment]
I think the requests are handled by an API and it use database, so it doesn't have to be a problem. I have just 1100 games and the detection looks to be instant - no long loading. It's the same as detection if giveaways have cards or not. There are lots of games and it is not a problem to compare all the giveaways with the huge database of all steam games.

**Comment by revilheart** [comment]
Getting the owned games will not be a problem, no matter how many you own. I'll just have to require the user's Steam API key.

**Comment by ldeman** [comment]
it's not a matter of retrieving the owned games i think you would have an issue with.  it's a matter of the massive removal request.

"search, remove entry, remove entry remove entry, search, search, search, search, search, repeated 4,400+ times".

if you do keep a comparison list after the first time check though that could work (similarly to what you did with stats)..  click the remove entry button, then it scans for the changes in your library first. then only tries to remove those changes.

**Comment by revilheart** [comment]
That wouldn't be the way I would do it anyway. I would do it like this: the script retrieves all pages of entered giveaways, saving all the App IDs and the code of the giveaways, then cross checks those App IDs with the App IDs of your owned games and makes requests to remove the entries in those giveaways. So it wouldn't be 4000+ requests. It would be the number of pages in the entered section with active giveaways plus the number of giveaways for the games you already own. Saving a cache of the owned games and only checking for new ones is a nice optimization, but it wouldn't change the number of requests.

**Comment by ldeman** [comment]
that's still a pretty significant amount of page requests for each and every time to press that button for some people. 

i'm upto page 833 personally. (41,600 entries divided by 50 per page)

can you have it save the amount of pages and figure the difference since last scan so it only has to check the latest x amount of pages?  the problem i foresee with that is manual or automatic removal of entries can screw with that page number.  so not quite as accurate.

**Comment by revilheart** [comment]
It's not every single entered page if you understood it like that. It's only the pages with active giveaways.

**Comment by ldeman** [comment]
yeah, it took me a while to wrap my head around.. as usual.. ^^  looking forward to it.
