### ISSUE TITLE
Feature request - hide entered GA, highlight games of interest

### ISSUE THREAD

**Issue by mmuh** [revilheart/rhSGST#5]
Is this where feature requests go? 
Big thanks and compliments on your work @revilheart , this script is really awesome! :)

I wanted to ask if you could add a feature or two, which are offered in another script but tend to glitch when both scripts are active.

The first would probably be rather simple - an option to hide entered GAs instead of just fading them out like ones "read".

The second would be any kind of automatic but removable highlighting/tag of all games i entered previous GAs for, or a manual one click custom game tag that can be used for quick but permanent highlighting of interesting games without bloating steams wishlist.
(i'm used to categorizing games in interesting (tag / sg2o custom wishlist = enter again), no tag (new to me, read store page), wait (tag) and uninterested (filter list).)

If those requests are more complicated and impracticable for others than i thought just forget them, it can be done with other scripts (not automatically by entering) but it's glitchy. Have a great day :)

**Comment by revilheart** [comment]
Yep, this is where they go. You're welcome, thanks for using it. :)

I'll see if I can add the option to hide entered giveaways.

Isn't the Game Tags feature useful for your second suggestion? If you wish the game to get an automatic upon entering I think I can add that.

**Comment by mmuh** [comment]
Cool, yes if that's technically a good option a auto-tag upon entering would do the trick just fine. If that tag would be customizeable it would be even better - then i could use a big ascii symbol for visibility.
Thank you for considering :)

**Comment by revilheart** [comment]
I meant just automatically adding a normal tag through https://github.com/revilheart/rhSGST#game-tags. You can test it out. :)

**Comment by mmuh** [comment]
Yes, i've tried your tags before and they work very well - in fact they brought me to the idea that your script could make the other script obsolete, if a "interesting/enter" tag (or highlight) of any kind would automatically be added to those games i entered at least once or if i had a button (like in SG2o a heart symbol) that puts a certain permanent tag on by a simple manual click on it.

**Comment by revilheart** [comment]
What do you think about this? If you have already entered for a game before, it gets a start next to its name:

![](http://i.imgur.com/kRHCTwZ.png)

**Comment by mmuh** [comment]
That way it would be incredibly much easier to decide what to enter without having to remember what exactly each game is, perfect solution! :)

In case of changed mind a game should be "unstarable" somehow though.

**Comment by revilheart** [comment]
Added both requests, but you can't unstar a game yet. I'll add that later. :)

**Comment by mmuh** [comment]
You are THE best, thank you so much revil! :)
Both features are working like a charm!

**Comment by revilheart** [comment]
You're welcome! :) Added the option to unstar a game.
