### ISSUE TITLE
[Enhancement] Make results grey if their value is zero in User's GA data

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#56]
I would love if the results with zero were written in grey color.  The table would be more readable then.

[Image of what it would look like.](http://i.imgur.com/1US7Jm3.png)

**Comment by ldeman** [comment]
you clicked "comment" just a hair to fast, the image didn't upload.  ;)

**Comment by gizellos** [comment]
No, there is a problem with the uploading. It has just 80 KB, it should be upload fast. It is not working currently. :(

**Comment by ldeman** [comment]
mhh yeah, i like this idea.. that does make it easier to read that chart.
