### ISSUE TITLE
[Bug] Shared Group is popping inside Avatar Popout

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#58]
i got squished to fix the tiny box issue i was having with this feature combined with dark theme, but it not being fully fixed made me realize this is happening without dark theme as well.

it's not popping out of the popout, it's popping inside the popout which causes a bunch of scroll bars.
![peek 2017-03-13 19-36](https://cloud.githubusercontent.com/assets/10275898/23881044/a4533cba-0825-11e7-9548-1f7fc3a7a781.gif)

**Comment by ldeman** [comment]
nevermind, it's a script load order thing.  for some reason having dark theme before rhSGST in load order messes it up for both.. its fine without dark theme, or fine with dark theme as long as rhSGST loads first (but not second).

**Comment by revilheart** [comment]
Weirdly I'm getting that issue here, and I don't use dark theme. Wonder if I messed it up in some update.

**Comment by ldeman** [comment]
lol, okay.  well dark theme seems to fix it whether enabled or disabled.  idk if that might help.  ^^

**Comment by revilheart** [comment]
Already found it. Might be the dark theme overriding the CSS rule.

**Comment by ldeman** [comment]
yeah since it has to be 2nd in the load order for it to fix it, that makes perfect sense.
