### ISSUE TITLE
Thread Marking Error

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#6]
I've ran across 3x separate threads that throw an error and never actually mark them thread, eventually you give up and it seems to still try in the background until it eventually errors out even if you refresh.

![screenshot from 2017-02-21 15-32-16](https://cloud.githubusercontent.com/assets/10275898/23186334/6257d6ec-f84c-11e6-89dc-c7e711ca6c66.png)

edit: you can go inside the thread and mark each page just fine, but not the full thread at once from the /discussions page

**Comment by ldeman** [comment]
this one is starting to be a lot more popular.  constantly getting it now on specific threads.

**Comment by revilheart** [comment]
Fixed

**Comment by ldeman** [comment]
excellent, thank you much!  =)
