### ISSUE TITLE
[BUG] Delivered Gifts Notifier Error

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#62]
noticed it wasn't working since i woke up with 2 wins with sent keys. and then checked console.
![screenshot from 2017-03-15 05-49-05](https://cloud.githubusercontent.com/assets/10275898/23945161/71cbca54-0943-11e7-8cd3-1fdfc0e6bc79.png)
![screenshot from 2017-03-15 05-50-06](https://cloud.githubusercontent.com/assets/10275898/23945164/74786398-0943-11e7-96c1-fbf82f30e9cd.png)

**Comment by revilheart** [comment]
I think the not received button is faded out the first 7 days, right? That might be what's causing it.

**Comment by ldeman** [comment]
correct, it is faded out for the first 7days.

**Comment by revilheart** [comment]
Could you right click it and take a screenshot of the inspect element panel?

**Comment by ldeman** [comment]
i had already marked it received. unsure if that will make a difference.
![image](https://cloud.githubusercontent.com/assets/10275898/23948798/b1c99668-0952-11e7-96c5-3a2170a42b60.png)

**Comment by revilheart** [comment]
Should be fixed, can you unmark it as received for a few seconds to refresh the page and see if it notifies?

**Comment by ldeman** [comment]
yep, that works.  thank you very much!  =)
