### ISSUE TITLE
[BUG] Entries Remover stuck on page 2 scan with error

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#63]
![image](https://cloud.githubusercontent.com/assets/10275898/23953119/a71fe5a0-0961-11e7-96a3-16afd87f0f0e.png)
(obviously ignore the first error)

**Comment by revilheart** [comment]
Is there a game without an image in page 2?

**Comment by ldeman** [comment]
yes, the type you are asking about as well as a whole lot of funky missing images that shouldn't be.
![image](https://cloud.githubusercontent.com/assets/10275898/23954575/ade29e1a-0965-11e7-85d8-d4dbe262a119.png)

**Comment by revilheart** [comment]
Yeah, it won't be possible to remove those without images. Will make the script ignore them in the next update.

**Comment by ldeman** [comment]
sounds good.  thanks ^^
