### ISSUE TITLE
[Enhancement] Load other last 5 active threads instead of going to the discussion

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#64]
There is the button **More >** in Active Discussion section and it is just a link to the discussion. I would expect loading other 5 active threads there, though.

I t would be much better. Could you implement it? You could use two buttons Next and Previous instead of the button. The button leading to the discussion doesn't have much sense, anyway.

**Comment by revilheart** [comment]
I don't see the point. That box is supposed to show only the 5 most recent discussions. Showing more would defeat that purpose and it would be more practical to just go to the discussions for that (why keep loading 5 new discussions each time and causing unnecessary server load when you can see all of them in the discussions page?).

So I'm not implementing that, sorry. Adding "wontfix" label because there isn't a "wontimplement" label and I can't add custom labels. :P

**Comment by gizellos** [comment]
You are right It doesn't have much sense. I just thought it could be good because of "AJAX feeling" - when you don't have to leave the current page and see all things be redrawn to see some other things.

**Comment by revilheart** [comment]
That makes sense for small things like the enter / leave giveaway button, but I don't see the point of viewing all discussions from the main page. In fact, I don't even see the point of Active Discussions. I never use it and I always go to the discussions page instead.

**Comment by ldeman** [comment]
> I don't even see the point of Active Discussions

well that one i don't use use, but it's nice to see if you are on the giveaways page and you see one of the 5 active comments is a announcement by CG, or some other really good hot topic that you may wanna jump in on immediately rather then check out GAs page 2 (or GAs in general if your new feature is enabled).  ^^

**Comment by gizellos** [comment]
The meaning of active discussions is that if a person doesn't intend to go to the discussion, they can see an interesting topic even without going to the discussion. So without it, the people would not see the topics. It is something like advertisements, just it is not for commerce.

**Comment by revilheart** [comment]
I spend 90% of my SG time on the discussions page, so maybe that's why I don't care about Active Discussions. :P

**Comment by gizellos** [comment]
Then you need something like Active giveaways instead. :D

**Comment by revilheart** [comment]
Active Wishlist Giveaways would be better for me, since I only enter giveaways for games that are on my wishlist. xD
