### ISSUE TITLE
[Enhancement] Add a link to the settings to the rhSGST button/menu

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#65]
I would like there would be also a link to the [rhSGST settings](https://www.steamgifts.com/account/profile/sync#rhSGST) in the rhSGST button/menu.

**Comment by gizellos** [comment]
I forgot the buttons itself is a link to the settings. You can close this topic (although it may be more clear if there would be also the section inside).

**Comment by revilheart** [comment]
I'd rather not add another item to the menu. And just clicking the button to go to the settings is way better than clicking the dropdown arrow and then clicking a link.
