### ISSUE TITLE
[Request] Go to first unread comment from /Discussions

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#7]
title pretty much covers it.. can that button also be extended to the list of discussions so It will just jump to the unread comment similar to the way the jump to last comment is on the /discussions page?
![_____](https://cloud.githubusercontent.com/assets/10275898/23224969/ecca3546-f8f5-11e6-80d6-3059edec6f0b.png)

**Comment by revilheart** [comment]
Yep, I knew this was going to be requested eventually. Will work on it. :)

**Comment by ldeman** [comment]
excellent, thanks yet again.  ^^

**Comment by revilheart** [comment]
Added

**Comment by ldeman** [comment]
Thanks Again!  =)
