### ISSUE TITLE
[Request] Thread Highlighter

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#8]
already requested on sg, but thought i'd make a "issue" report here so it can be kept track of.

just a basic button of some type off to the side of the topic title that will cause it to highlight that specific thread on the /discussions page.  another part of the "tracking" that would make things easier to follow.

in no rush at all though, it can be put off for as long as you need.   thanks again.

**Comment by revilheart** [comment]
Any highlight color in mind?

**Comment by ldeman** [comment]
probably would prefer sighery's highlighter color from racharts script, but that's because it's friendly to the dark theme with a tickbox.  so that may require 2x shades.
whatever is easiest really though, some shade of green or blue that maybe friendly to dark and nodark users both without the toggle i'd say probably would be best if you can find it.

**Comment by revilheart** [comment]
Added, let me know if the color isn't nice.

**Comment by ldeman** [comment]
color looks fine to me, but ever since the update page loads and dark theme load time dropped significantly/horribly. 
![peek 2017-02-23 07-57](https://cloud.githubusercontent.com/assets/10275898/23261853/ef3692d6-f99d-11e6-8671-890b0ad8038e.gif)

**Comment by revilheart** [comment]
Hmm, can you try disabling each of the new features to see what's impacting it?

**Comment by ldeman** [comment]
it seems to be the discussion highlighter.  whether there is a highlight or not.  as soon as it's disabled the page loads 10x faster.

**Comment by revilheart** [comment]
See if the new update fixes it.

**Comment by ldeman** [comment]
yes, that works beautifully now. =)
thanks again for another amazing feature/option.  ^^
