### ISSUE TITLE
[Bug] Export

### ISSUE THREAD

**Issue by ldeman** [revilheart/rhSGST#9]
Attempting to export data now gives a network error instead of actually downloading. 
![image](https://cloud.githubusercontent.com/assets/10275898/23264839/63e25796-f9a8-11e6-9343-61af9d94c333.png)

**Comment by revilheart** [comment]
Is it fixed with the new version?

**Comment by ldeman** [comment]
sorry, ran to town to buy my kids a cple cheap laptops.  yes though, i can export again.  (went from 1.1mb backup to 3.8mb backup)  ^^

thanks again for the prompt fix.  xD

**Comment by revilheart** [comment]
No problem, glad it worked. xD
